spring:
  datasource:
    url: jdbc:mysql://10.19.140.200:32143/cc
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
    cc: DEBUG
  file: /var/log/cc-terminal.log